spring:
    application:
        name: Pedidos
    datasource:
        url: jdbc:postgresql://localhost:5432/pedidos
        username: postgres
        password: admin
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none